format_version: 4

pipelines:
  "mhs-dns-images":
    group: mhs
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - build:
          clean_workspace: true
          jobs:
            dns_image:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker_dns
      - test:
          clean_workspace: true
          jobs:
            dns_image:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_docker_dns
