format_version: 4
pipelines:
  "prm-mhs-infra-opentest":
    group: mhs
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      integration_adaptors:
        git: https://github.com/tomzo/integration-adaptors.git
        branch: deductions
        destination: integration-adaptors
      docker:
        pipeline: mhs-docker-images
        stage: build
    environment_variables:
      NHS_ENVIRONMENT: opentest
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            deploy:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks tf_plan create
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks tf_apply
      - test:
          clean_workspace: true
          jobs:
            e2e:
              resources:
                - mhs-opentest
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: integration-adaptors
                    arguments:
                      - -c
                      - ./tasks e2e_tests
